#Given: A protein string of length at most 1000 aa.
#Return: The total number of different RNA strings from which the protein could have been translated, modulo 1,000,000. (Don't neglect the importance of the stop codon in protein translation.)

def count_rna_strings(protein):
    codon_table = {
        'A': 4, 'C': 2, 'D': 2, 'E': 2, 'F': 2,
        'G': 4, 'H': 2, 'I': 3, 'K': 2, 'L': 6,
        'M': 1, 'N': 2, 'P': 4, 'Q': 2, 'R': 6,
        'S': 6, 'T': 4, 'V': 4, 'W': 1, 'Y': 2,
        'Stop': 3
    }

    total = 3  # Counting the stop codon
    for aa in protein:
        total *= codon_table[aa]
        total %= 10**6  # Modulo 1,000,000

    return total

# Example usage:
protein = "MRHIVVEVYYREHQIWKHYTVGILIERGVITDTHNYQHGDNFTTHWPKHNCPMIEHLKNIDSDKMFKWRDKYVGYRPISGNGNCIMGFAIWGPVNMRALNKEACCPTAQAIYQNWVWRAFMQDWPAEANALIFFVTTTFLVTDICTMRFIFMSDSTVQRKKDFQCTGINGTGAVHNDQVSVQPTSMNGSRHDYSDDVTTIQSIKHAFYFKQFYWGRTKWYPCRLLSGRPPRIWQFNLDIEHIQLSGLIWPEELVKYTAWCDFTIWGYTCQLWCYFDMCSWAAGQSYCTFKVAITAFWDHDPVENLTRHFMAHFTQNTAEHYYACACCGELQHQNFNGETKPGTKYCAPFEHWVNSCMTWEDEDNIVISAGHITSMINLHLIPAKRSSSTMSGGIIVNEGQTHFICQHSTIWPAFPHWNEHKAPLKTYEKREYKQFGVPRPEWDVKREPPAAPFWCLEKDELSCGNARHCGRGQVTRSWCFVGIIDKQRSEKRLCDKDYPDGWLLGHCPICHLCLQLCPDAVLLSRKVTDSGLLQHMFIPWTYCSYMMGDSDFTAGQLITYDYLSIAQTAPEDSHQGLFCCVIEGPMYGNSMYYACGHTWWYSPSLNSGACNNKQDEWECAFQDPIVWIPENNRHWCHCKLWQMCWCTPYCPICGGNLVIYLKNAGRVEATAFYIRIMDALSRPERCASHHVWSWTVTFRMMGGTGACLFTIDYVWTNKTMHDWHTTQENTGPPPDTCNDSHSPIGFPKPCALPITFSMNDMQGAAPSWFDERTKRSHFPNMPMEMQATYQILPKLPAPHDKWETPARQHMMTPEVPCYDKFAAIGEHTLWIKQYEQWSRFQRIIRIFSAELYETATHDSRYILFMSCKLYHCPSIQLRVSALWLKQEILTQGQSATLKRSFMDKKPVAGRFCEQKIDPRWGGMPKSGMKSFSMGFAEWILNRPHVIEQNTCECGFIGMACREMKKMIIFHCAFQYTKLYYMYHCGNQHAMSHVLSSGLR"
result = count_rna_strings(protein)
print(result)
